openapi: 3.0.0
info:
  title: Product Service API
  description: API for fetching products
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get full list of products
      operationId: getProductsList
      tags:
        - Products
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Get product by Id
      operationId: getProductsById
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          description: Id of the product
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the product
        description:
          type: string
          description: Product description
        title:
          type: string
          description: Product title
        price:
          type: number
          format: integer
          description: Product price