service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

# you can overwrite defaults here
  stage: dev

# you can add statements to the Lambda function's IAM Role here
  iam:
   role:
     statements:
       - Effect: "Allow"
         Action:
           - "s3:ListBucket"
         Resource: "arn:aws:s3:::import-bucket-task5/*"
       - Effect: "Allow"
         Action:
           - "s3:*"
         Resource: "arn:aws:s3:::import-bucket-task5/*"


# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  importProductsFile:
    handler: handler.importProductsFiles
    events:
     - httpApi:
         path: /import/{name}
         method: get

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
